name: Build Job
on: 
  push:
    branches: 
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven Build
        run: mvn install


  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Run tests on main branch
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

  Deploy:
      runs-on: ubuntu-latest
      needs: Testing
      if: github.ref == 'refs/heads/main'
      steps:
        - name: Code checkout
          uses: actions/checkout@v4

        - name: Deploy to Production
          run: echo "Deploying to production server..."